AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Database schema with GSIs

Resources:
  WsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WsTable
      BillingMode: PAY_PER_REQUEST # set capacity to on-demand mode

      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S

        - AttributeName: skey
          AttributeType: S

      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: wsInvertIndex
          KeySchema:
            - AttributeName: skey
              KeyType: HASH

            - AttributeName: connectionId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyTable
      AttributeDefinitions:
        - AttributeName: P_K
          AttributeType: S

        - AttributeName: S_K
          AttributeType: S

        - AttributeName: SocialConnectionUsername # for follower/following sorted by username
          AttributeType: S

        - AttributeName: PublicSearch
          AttributeType: N

        - AttributeName: FilterDataName
          AttributeType: S

        - AttributeName: AudienceDynamicField
          AttributeType: S

        - AttributeName: FollowRequestReceiver
          AttributeType: S

        - AttributeName: timestamp
          AttributeType: N

        - AttributeName: audienceId
          AttributeType: S

      KeySchema:
        - AttributeName: P_K
          KeyType: HASH

        - AttributeName: S_K
          KeyType: RANGE

      GlobalSecondaryIndexes:
        - IndexName: SortedSocialRelationByUsernameIndex
          KeySchema:
            - AttributeName: P_K
              KeyType: HASH

            - AttributeName: SocialConnectionUsername
              KeyType: RANGE
          Projection:
            ProjectionType: ALL #TODO: only project required fields
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

        - IndexName: SearchByUsernameIndex
          KeySchema:
            - AttributeName: PublicSearch
              KeyType: HASH

            - AttributeName: FilterDataName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL #TODO: only project required fields
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

        - IndexName: AllClubsOfAudienceIndex # All the clubs entered by a user whether just attended, participated or organized (owned)
          KeySchema:
            - AttributeName: audienceId
              KeyType: HASH

            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL #TODO: only project required fields
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

        - IndexName: AudienceDynamicDataIndex # for actvie join request, particpants, kicked out people
          KeySchema:
            - AttributeName: P_K
              KeyType: HASH

            - AttributeName: AudienceDynamicField
              KeyType: RANGE
          Projection:
            ProjectionType: ALL #TODO: only project required fields
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

        - IndexName: ReceivedFollowRequestIndex
          KeySchema:
            - AttributeName: FollowRequestReceiver
              KeyType: HASH

            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL #TODO: only project required fields
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
