version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Websocket-Services"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fx764orwneqn"
s3_prefix = "Websocket-Services"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
