version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Websocket-Services"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mh05w5uu8qtp"
s3_prefix = "Websocket-Services"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
