version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Express-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fx764orwneqn"
s3_prefix = "Express-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
