AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  user-service-functions

  SAM Template

Globals:
  Function:
    Timeout: 3

Resources:
  UserServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: UserServices/
      Handler: handler.handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "MyTable"

      Events:
        APIRoot:
          Type: Api
          Properties:
            Path: /
            Method: get

        UserList:
          Type: Api
          Properties:
            Path: /users
            Method: get

        CreateUser:
          Type: Api
          Properties:
            Path: /users/create
            Method: post

        GetUserById:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: get

        UpdateUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: patch

        SearchUserByUsername:
          Type: Api
          Properties:
            Path: /users/query/{username}
            Method: get

        ListFollowing: #use headers for sorting by username
          Type: Api
          Properties:
            Path: /users/{userId}/following
            Method: get

        ListFollowers: #use headers for sorting by username
          Type: Api
          Properties:
            Path: /users/{userId}/followers
            Method: get

        SendFollowRequest:
          Type: Api
          Properties:
            Path: /users/{userId}/follow-requests
            Method: post

        ListSentFollowRequests: #use headers for sorting by username
          Type: Api
          Properties:
            Path: /users/{userId}/follow-requests/sent
            Method: get

        ListReceivedFollowRequests:
          Type: Api
          Properties:
            Path: /users/{userId}/follow-requests/received
            Method: get

        DeleteFollowRequest: #only sender can perform this action
          Type: Api
          Properties:
            Path: /users/{userId}/follow-requests/sent
            Method: delete

        ResponseToFollowRequest: # only receiver can perform this action (appropriate headers are required)
          Type: Api
          Properties:
            Path: /users/{userId}/follow-requests/received
            Method: post

Outputs:
  UserServiceAPIs:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"

  UserServiceFunction:
    Description: "User Service  Lambda Function ARN"
    Value: !GetAtt UserServiceFunction.Arn

  UserServiceFunctionIamRole:
    Description: "Implicit IAM Role created for Social Events function"
    Value: !GetAtt UserServiceFunction.Arn
