version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "clubDatabaseStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fx764orwneqn"
s3_prefix = "clubDatabaseStack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
