AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  club-database-service

  Sample SAM Template for club-database-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: python3.7

Resources:
  ClubDatabaseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: club-database-table
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S

        - AttributeName: clubId
          AttributeType: S

      KeySchema:
        - AttributeName: username
          KeyType: HASH

        - AttributeName: clubId
          KeyType: RANGE

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ClubDatabaseFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: club-database-handler/
      Handler: app.lambda_handler
      # Runtime: python3.7
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ClubDatabaseTable

      Events:
        CreateClub:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /clubs/create
            Method: post

        ListClubs:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /clubs
            Method: get

        GetAllUserClubs:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /clubs/{username}
            Method: get

        GetSpecificClub:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /clubs/{username}/{clubId}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ClubDatabaseFunction:
    Description: "Club Database Function ARN"
    Value: !GetAtt ClubDatabaseFunction.Arn
  ClubDatabaseFunctionIamRole:
    Description: "Implicit IAM Role created for Club Database Function"
    Value: !GetAtt ClubDatabaseFunctionRole.Arn
