AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  user-database-service

  Sample SAM Template for user-database-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

# Globals is a section in your SAM template to define properties common to all your Serverless Function and APIs. All the AWS::Serverless::Function and AWS::Serverless::Api resources will inherit the properties defined here
Globals:
  # for serverless functions
  Function:
    Timeout: 3
    Runtime: python3.7
  # for api
  # Api:

Resources:
  UserProfileBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mootclub-user-profile-bucket # if any bucket with the same name exists on AWS servers globally i.e. in any user's account, you can't use that name

  UserProfileBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: "UserProfileBucket"
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: "UserProfileBucket"
                  - "/*"
            Principal: "*"

          - Action:
              - "s3:PutObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: "UserProfileBucket"
                  - "/*"
            Principal: "*"

          - Action:
              - "s3:PutObjectAcl"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: "UserProfileBucket"
                  - "/*"
            Principal: "*"

  UserDatabaseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: user-database-table
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S

        - AttributeName: username
          AttributeType: S

      KeySchema:
        - AttributeName: userId
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: UsernameIndex
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  UserDatabaseReadFunction:
    Type: AWS::Serverless::Function
    Properties:
      # codeUri points to the name of folder where it can look for desired code
      CodeUri: user-database-handler/
      Handler: handler.app
      # Runtime: python3.7
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserDatabaseTable
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: get

        AllUsers:
          Type: Api
          Properties:
            Path: /users
            Method: get

        GetUser:
          Type: Api
          Properties:
            Path: /users/{userId}
            Method: get

        GetUserByUsername:
          Type: Api
          Properties:
            Path: /users/query/{username}
            Method: get

  UserDatabaseModifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      # codeUri points to the name of folder where it can look for desired code
      CodeUri: user-database-handler/
      Handler: handler.app
      Timeout: 60 #todo: find optimal value for timeout since putting an image object might take longer time
      # Runtime: python3.7

      # can't use only writePolicy because it doesn't have delete permissions
      # todo: create a custom policy with write and delete permissions for dynamodb
      # Policies:
      #   - DynamoDBCrudPolicy:
      #       TableName: !Ref UserDatabaseTable

      # this role allows as name suggests - CUD operation for dynamodb and putObject & deleteObject permission for s3 (all resources)
      # todo: change its permission from all resources to only this table
      Role: arn:aws:iam::556316647006:role/user-data-modify-dynamodb_s3-role

      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /users/create
            Method: post

        UpdateUser:
          Type: Api
          Properties:
            Path: /users/{userId}/update
            Method: patch

        DeleteUser:
          Type: Api
          Properties:
            Path: /users/{userId}/delete
            Method: delete

        UploadProfileImage:
          Type: Api
          Properties:
            Path: /users/{userId}/uploadImage
            Method: post

  FollowerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Followers
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: followerUsername
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: followerUsername
          KeyType: RANGE

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  FollowingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Following
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: followingUsername
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: followingUsername
          KeyType: RANGE

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  SocialRelationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: user-database-handler/
      Handler: socialRelationHandler.app
      # Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FollowerTable
        - DynamoDBCrudPolicy:
            TableName: !Ref FollowingTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDatabaseTable

      Events:
        CheckFollowing:
          Type: Api
          Properties:
            Path: /users/{userId}/follow/{username}/{followingUsername}
            Method: get
        Following:
          Type: Api
          Properties:
            Path: /users/{userId}/following/{username}
            Method: get

        Followers:
          Type: Api
          Properties:
            Path: /users/{userId}/followers/{username}
            Method: get

        AddToFollowing:
          Type: Api
          Properties:
            Path: /users/{userId}/following/add/{followingUserId}
            Method: post

        DeleteFromFollowing:
          Type: Api
          Properties:
            Path: /users/{userId}/following/delete/{followingUserId}
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RootApi:
    Description: "API Gateway endpoint URL for Prod stage for UserDatabaseReadFunction "
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  UserDatabaseReadFunction:
    Description: "UserDatabaseRead Lambda Function ARN"
    Value: !GetAtt UserDatabaseReadFunction.Arn

  # UserDatabaseModifyFunction:
  #   Description: "UserDatabaseModify Lambda Function ARN"
  #   Value: !GetAtt UserDatabaseModifyFunction.Arn

  UserDatabaseReadFunctionIamRole:
    Description: "Implicit IAM Role created for UserDatabaseReadFunction"
    Value: !GetAtt UserDatabaseReadFunctionRole.Arn
  # UserDatabaseModifyFunctionIamRole:
  #   Description: "Implicit IAM Role created for UserDatabaseModifyFunction"
  #   Value: !GetAtt UserDatabaseModifyFunctionRole.Arn
