version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SQS-Lambdas-Stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mh05w5uu8qtp"
s3_prefix = "SQS-Lambdas-Stack"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
