version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "follow"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13flfkh9dp8yy"
s3_prefix = "follow"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
